import { chromium } from 'playwright';
const args = ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'];
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, deviceScaleFactor: 1 });
const page = await ctx.newPage();
await page.goto('http://localhost:4820/');
await page.waitForTimeout(800);
await page.locator('#t-start').tap();
await page.waitForTimeout(2000);
const m = () => page.evaluate(() => new Promise((res) => { let n = 0; const t0 = performance.now(); const f = () => { n++; if (performance.now() - t0 < 2500) requestAnimationFrame(f); else res(n / 2.5); }; requestAnimationFrame(f); }));
console.log('base', await m());
await page.evaluate(() => __game.setSetting('shadows', false));
await page.waitForTimeout(3000);
console.log('shadows off', await m());
await page.evaluate(() => { __gfx.renderer.setPixelRatio(0.75) });
console.log('shadows off 0.75', await m());
await page.evaluate(() => { __gfx.renderer.setPixelRatio(1) });

await page.evaluate(() => { __gfx.renderer.shadowMap.autoUpdate = false; });
console.log('noshadowupdate', await m());
await page.evaluate(() => { __game.game.env.visible = false; });
console.log('noenv', await m());
await page.evaluate(() => { __game.game.root.visible = false; });
console.log('noroot', await m());
await page.evaluate(() => { __gfx.scene.children.forEach(c=>c.visible=false) });
console.log('nothing', await m());
await page.evaluate(() => { __gfx.renderer.setPixelRatio(0.5) });
console.log('nothing-halfres', await m());
await b.close();
