import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await (await b.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, deviceScaleFactor: 2 })).newPage();
page.on('console', (m) => (m.type() === 'error' || m.type() === 'warning') && console.log('[c]', m.text()));
page.on('pageerror', (e) => console.log('[pe]', e.message, e.stack));
await page.goto('http://localhost:4820/?debug');
await page.waitForTimeout(1200);
await page.locator('#t-start').tap({ force: true });
await page.waitForTimeout(1500);
if (process.env.EV) await page.evaluate(process.env.EV);
await page.waitForTimeout(Number(process.env.W || 2500));
await page.screenshot({ path: 'shots/q.png' });
if (process.env.OUT) console.log(await page.evaluate(process.env.OUT));
console.log(await page.evaluate(() => JSON.stringify({ perf: window.__perf, geo: __gfx.renderer.info.memory, meshes: (() => { let n = 0; __gfx.scene.traverse((o) => { if (o.isMesh && o.visible) n++; }); return n; })() })));
await b.close();
